### ISSUE TITLE
READMEの誤字

### ISSUE THREAD

**Issue by PeterTakahashi** [lightondust/graphlandQ#17]
`pip install -r requirments.txt`を
`pip3 install -r requirements.txt`にしてください。
ファイル名に誤字があります

**Comment by lightondust** [comment]
気がついていなくてすみません。

ファイル名を直しました。

`pip` か `pip3`かに関しては、仮想環境で使うことを想定しているので、`pip`のままにしました。
その代わりに仮想環境に関するリンクをREADMEに追加しました。
